

function [frames, descriptors] = PhowFeature(img)
% DESCRIPTION: Generate Multi-Scale Color Dense SIFT local features for a given image.
% INPUT:       %img             Image from which local features are to be
%                               extracted
% OUTPUT:      %frames          Descriptor information
%              %descriptors     Extracted local features.

    % Import project configuration i.e. 'Configuration.m'
    Configuration;

    % Generate Multi-Scale Color Dense SIFT local features using 
    % 'vl_phow()' wrapper
    [frames, descriptors] = vl_phow(img, ...
                                    'Verbose', Phow.Verbose, ...
                                    'Sizes', Phow.Sizes, ...
                                    'Fast', Phow.Fast, ...
                                    'Step', Phow.Step, ...
                                    'Color', Phow.Color, ...
                                    'ContrastThreshold', Phow.ContrastThreshold, ...
                                    'WindowSize', Phow.WindowSize, ...
                                    'Magnif', Phow.Magnif, ...
                                    'FloatDescriptors', Phow.FloatDescriptors);

end

